"""
Report Generator - Generates human-readable reports from clinic results.

Supports multiple output formats:
- Markdown (default)
- Plain text
- JSON
"""

from typing import List, Optional
from datetime import datetime

from tokenpulse.checks.check_result import CheckResult, HealthStatus
from tokenpulse.clinic.data_structures import ClinicReport


class ReportGenerator:
    """
    Report Generator creates human-readable reports from clinic results.

    The generator supports multiple output formats and can include
    visualization data for charts and graphs.
    """

    # Status emojis for display
    STATUS_EMOJI = {
        HealthStatus.GREEN: "🟢",
        HealthStatus.YELLOW: "🟡",
        HealthStatus.RED: "🔴",
        HealthStatus.SKIP: "⚪",
    }

    # Category display names
    CATEGORY_NAMES = {
        "blood": "概率与分布检查",
        "neural": "敏感度与鲁棒性检查",
        "bone": "表征与权重检查",
        "immune": "校准与置信度检查",
    }

    # Category descriptions
    CATEGORY_DESCRIPTIONS = {
        "blood": "检查模型的概率分布特性，包括词表利用率、输出熵等",
        "neural": "检查模型对输入扰动的敏感度和鲁棒性",
        "bone": "检查模型的内部表征和权重分布",
        "immune": "检查模型的置信度校准和不确定性表达",
    }

    def __init__(self, template: str = "default"):
        """
        Initialize the report generator.

        Args:
            template: Report template name (default, minimal, detailed)
        """
        self.template = template

    def generate_markdown(self, report: ClinicReport) -> str:
        """
        Generate a Markdown format report.

        Args:
            report: Clinic report to format

        Returns:
            Markdown formatted report string
        """
        lines = []

        # Header
        lines.append("# TokenPulse 体检报告")
        lines.append("")

        # Basic information
        lines.append("## 基本信息")
        lines.append("")
        lines.append(f"- **报告ID**: {report.report_id}")
        lines.append(f"- **生成时间**: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"- **模型**: {report.model_info.get('model_id', 'Unknown')}")
        lines.append(f"- **体检套餐**: {report.check_preset}")
        lines.append(f"- **执行耗时**: {report.execution_time:.2f}s")
        lines.append("")

        # Overall assessment
        lines.append("## 总体评估")
        lines.append("")
        status_emoji = self.STATUS_EMOJI.get(report.overall_health_status, "⚪")
        lines.append(f"**健康状态**: {status_emoji} {report.overall_health_status.value.upper()}")
        lines.append("")
        lines.append(f"**健康分数**: {report.overall_health_score:.1f}/100")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Detailed results by category
        lines.append("## 详细检查结果")
        lines.append("")

        # Group results by category
        categories = {"blood": [], "neural": [], "bone": [], "immune": []}
        for result in report.check_results:
            if result.check_category in categories:
                categories[result.check_category].append(result)

        for cat_key, cat_results in categories.items():
            if not cat_results:
                continue

            cat_name = self.CATEGORY_NAMES.get(cat_key, cat_key)
            lines.append(f"### {cat_name}")
            lines.append("")
            lines.append(f"*{self.CATEGORY_DESCRIPTIONS.get(cat_key, '')}*")
            lines.append("")

            for result in cat_results:
                lines.extend(self._format_check_result(result))
                lines.append("")

        # Skipped checks
        if report.checks_skipped:
            lines.append("### 未执行的检查项")
            lines.append("")
            for check_name in report.checks_skipped:
                lines.append(f"- {check_name}")
            lines.append("")

        # Recommendations
        if report.recommendations:
            lines.append("---")
            lines.append("")
            lines.append("## 建议与改进方向")
            lines.append("")
            for i, rec in enumerate(report.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by TokenPulse - LLM模型诊断工具*")

        return "\n".join(lines)

    def _format_check_result(self, result: CheckResult) -> List[str]:
        """
        Format a single check result for Markdown.

        Args:
            result: Check result to format

        Returns:
            List of Markdown lines
        """
        lines = []
        status_emoji = self.STATUS_EMOJI.get(result.health_status, "⚪")

        # Check name with status
        check_display = result.check_name.replace("_", " ").title()
        lines.append(f"#### {status_emoji} {check_display}")
        lines.append("")

        # Status and score
        lines.append(f"- **状态**: {result.health_status.value}")
        lines.append(f"- **分数**: {result.health_score:.1f}/100")

        # Execution metadata
        if result.execution_time > 0:
            lines.append(f"- **执行时间**: {result.execution_time:.2f}s")
        if result.samples_used > 0:
            lines.append(f"- **样本数量**: {result.samples_used}")

        lines.append("")

        # Error message if any
        if result.has_error():
            lines.append(f"**错误**: {result.error_message}")
            return lines

        # Key metrics
        if result.raw_metrics:
            lines.append("**关键指标**:")
            lines.append("")
            for key, value in self._summarize_metrics(result.raw_metrics).items():
                lines.append(f"- {key}: {value}")

        # Interpretation
        lines.append("")
        interpretation = result.get_interpretation() if hasattr(result, 'get_interpretation') else ''
        if interpretation:
            lines.append(f"*{interpretation}*")

        return lines

    def _summarize_metrics(self, metrics: dict) -> dict:
        """
        Summarize metrics for display.

        Args:
            metrics: Raw metrics dictionary

        Returns:
            Summarized metrics for display
        """
        summary = {}

        # Key metrics to display
        display_keys = [
            ("utilization_ratio", "词表利用率", lambda x: f"{x:.1%}"),
            ("type_token_ratio", "类型token比", lambda x: f"{x:.2f}"),
            ("ece", "ECE", lambda x: f"{x:.3f}"),
            ("accuracy", "准确率", lambda x: f"{x:.1%}"),
            ("mean_confidence", "平均置信度", lambda x: f"{x:.1%}"),
            ("coefficient_of_variation", "变异系数", lambda x: f"{x:.3f}" if isinstance(x, (int, float)) else f"{x.get('mean', 0):.3f}"),
            ("top_token_consistency", "Top-token一致性", lambda x: f"{x:.1%}" if isinstance(x, (int, float)) else f"{x.get('mean', 0):.1%}"),
        ]

        for key, display_name, formatter in display_keys:
            if key in metrics:
                try:
                    value = metrics[key]
                    if isinstance(value, dict) and "mean" in value:
                        summary[display_name] = formatter(value["mean"])
                    else:
                        summary[display_name] = formatter(value)
                except (KeyError, TypeError, ValueError):
                    pass

        return summary

    def generate_text(self, report: ClinicReport) -> str:
        """
        Generate a plain text format report.

        Args:
            report: Clinic report to format

        Returns:
            Plain text formatted report string
        """
        lines = []

        # Header
        lines.append("=" * 60)
        lines.append("TokenPulse 体检报告")
        lines.append("=" * 60)
        lines.append("")

        # Basic info
        lines.append(f"报告ID: {report.report_id}")
        lines.append(f"生成时间: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"模型: {report.model_info.get('model_id', 'Unknown')}")
        lines.append(f"体检套餐: {report.check_preset}")
        lines.append("")

        # Overall status
        lines.append("-" * 60)
        lines.append(f"总体状态: {report.overall_health_status.value.upper()}")
        lines.append(f"健康分数: {report.overall_health_score:.1f}/100")
        lines.append("-" * 60)
        lines.append("")

        # Check results
        lines.append("检查结果:")
        lines.append("")
        for result in report.check_results:
            status = f"[{result.health_status.value.upper()}]"
            score = f"({result.health_score:.1f}/100)"
            lines.append(f"  {status} {result.check_name}: {score}")

        # Recommendations
        if report.recommendations:
            lines.append("")
            lines.append("建议:")
            for i, rec in enumerate(report.recommendations, 1):
                lines.append(f"  {i}. {rec}")

        lines.append("")
        lines.append("=" * 60)

        return "\n".join(lines)

    def generate_json(self, report: ClinicReport) -> str:
        """
        Generate a JSON format report.

        Args:
            report: Clinic report to format

        Returns:
            JSON formatted report string
        """
        import json
        return json.dumps(report.to_dict(), indent=2, ensure_ascii=False, default=str)
